import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home({repo}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1>home</h1>
        <h2> "subscribers_count" {repo.subscribers_count}</h2>
        <h3>new data</h3>
      </main>
    </>
  )
}


export async function getStaticProps() {
  try{
    const res = await fetch('https://api.github.com/repos/vercel/next.js')
    const repo = await res.json()
    console.log("data fetched");
    return { props: { repo } }
  }catch(err){
    console.log("failed to get static props");
  }
}
 
